# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - gosimple       # Simplify code
    - govet          # Reports suspicious constructs
    - ineffassign    # Detects ineffectual assignments
    - staticcheck    # Static analysis
    - typecheck      # Type checks
    - unused         # Checks for unused constants, variables, functions
    - gofmt          # Checks if code was gofmt-ed
    - goimports      # Checks import statements are formatted
    - misspell       # Finds commonly misspelled words
    - gosec          # Security checker
    - revive         # Fast, configurable, extensible linter
    - unconvert      # Removes unnecessary type conversions
    # Disabled for now - too opinionated
    # - unparam        # Reports unused function parameters
    # - gocyclo        # Computes cyclomatic complexity
    # - dupl           # Code clone detection
    # - goconst        # Finds repeated strings
    # - godot          # Checks if comments end in a period
    # - lll            # Reports long lines
    # - gci            # Controls Go package import order
    # - gocritic       # Provides diagnostics
    - bodyclose      # Checks HTTP response bodies are closed
    # - noctx          # Finds HTTP requests without context (too strict for tests)
    - rowserrcheck   # Checks SQL rows.Err is checked
    - sqlclosecheck  # Checks SQL Close() is called
    - wastedassign   # Finds wasted assignment statements

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*go.uber.org/zap.Logger).Sync

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Performance optimization, not critical

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/tareqmamari/logs-mcp-server

  misspell:
    locale: US

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path provided as taint input (needed for dynamic config)
    severity: medium
    confidence: medium

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
        - govet
      severity: error
