# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - revive
    - unconvert
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*go.uber.org/zap.Logger).Sync

  goimports:
    local-prefixes: github.com/tareqmamari/logs-mcp-server

  gosec:
    excludes:
      - G104
      - G304
