# GoReleaser configuration for logs-mcp-server
# https://goreleaser.com

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: logs-mcp-server
    binary: logs-mcp-server
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore specific OS/arch combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - typo
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# Sign artifacts
# Note: Requires cosign for production releases
# Disabled for snapshots - enable by installing cosign: brew install cosign
# signs:
#   - cmd: cosign
#     env:
#       - COSIGN_EXPERIMENTAL=1
#     certificate: '${artifact}.pem'
#     args:
#       - sign-blob
#       - '--output-certificate=${certificate}'
#       - '--output-signature=${signature}'
#       - '${artifact}'
#       - "--yes"
#     artifacts: checksum
#     output: true
#     signature: '${artifact}.sig'

# Generate SBOM (Software Bill of Materials)
# Note: Requires syft (brew install syft)
# Disabled for now - uncomment and install syft to enable
# sboms:
#   - id: archive
#     artifacts: archive
#   - id: source
#     artifacts: source

# Docker images (optional - can be enabled if needed)
# dockers:
#   - image_templates:
#       - "ghcr.io/tareqmamari/logs-mcp-server:{{ .Version }}-amd64"
#       - "ghcr.io/tareqmamari/logs-mcp-server:latest-amd64"
#     use: buildx
#     goos: linux
#     goarch: amd64
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"

# Release configuration
release:
  github:
    owner: tareqmamari
    name: cloud-logs-mcp
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## IBM Cloud Logs MCP Server {{ .Version }}

    Release of IBM Cloud Logs Model Context Protocol (MCP) server.

    ### Installation

    Download the appropriate archive for your platform below.

  footer: |
    ---

    **Full Changelog**: https://github.com/tareqmamari/cloud-logs-mcp/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap
brews:
  - name: logs-mcp-server
    repository:
      owner: tareqmamari
      name: homebrew-tap
      branch: main
    homepage: https://github.com/tareqmamari/logs-mcp-server
    description: "IBM Cloud Logs MCP Server - Model Context Protocol server for IBM Cloud Logs"
    license: "UNLICENSED"
    test: |
      system "#{bin}/logs-mcp-server", "--version"
    install: |
      bin.install "logs-mcp-server"
    caveats: |
      To use logs-mcp-server, you need to configure:
        1. Get your IBM Cloud API key: https://cloud.ibm.com/iam/apikeys
        2. Set environment variables:
           export LOGS_API_KEY='your-api-key'
           export LOGS_SERVICE_URL='https://instance-id.api.region.logs.cloud.ibm.com'
           export LOGS_REGION='us-south'
        3. Configure in Claude Desktop

      For more information, see: https://github.com/tareqmamari/logs-mcp-server

# Announce release (optional)
# announce:
#   skip: '{{gt .Patch 0}}'  # Skip patch releases
